### ISSUE TITLE
exported image missing text

### ISSUE THREAD

**Issue by xiaoqiangch** [tfc/pandoc-drawio-filter#3]
I use pandoc to export the drawio (svg) images in the markdown document to docx ,
and find that although the image was exported, the text in the text in the pictures are missing .

the code in the obsidian setting with pandoc:

-F /Library/Frameworks/Python.framework/Versions/3.10/bin/pandoc-drawio

this image is supposed to have text:

![image](https://user-images.githubusercontent.com/16594186/210134044-dc033e6f-cdbf-48d2-88e0-4b083240c494.png)

**Comment by tfc** [comment]
Hello!

I'd like to help you, but this description alone does not allow to help you. 
In order to get help, please provide a little minimal example project that others can use to build and reproduce your problem.
